import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import cn from 'classnames'
import Header from '@/components/ui/Header'
import BottomNav from '@/components/ui/BottomNav'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Threads',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={cn('antialiased h-full font-sans', inter.className)}>
        <Header />
        {children}
        <BottomNav />
      </body>
    </html>
  )
}
